package-lock.json
src/components/schoolComponent.tsx

Update package-lock, fix suggestions list

---

src/shared/StyledCreatableSelect.tsx
src/shared/StyledSelect.tsx

Change color scheme for focused / hovered elements

---

package-lock.json
src/api/hacker.ts
src/config/APIRoute.ts
src/config/constants.ts
src/config/index.ts
src/config/statsResponse.ts

Add api endpoint

---

src/api/auth.ts

Clear hacker cache upon logout

---

src/config/constants.ts

Remove trailing slash

---

src/shared/Form/FormikElements/Checkbox.tsx

Add flex to make checkbox inline with label

---

src/App.tsx
src/Dashboard/HackerDashboard.tsx
src/Dashboard/Main.tsx
src/Dashboard/StaffDashboard.tsx
src/Dashboard/View.tsx
src/config/userTypes.ts

Fixes #189.
Makes it such that a different dashboard is loaded up depending on which userType someone is.

Refactor dashboard

---

src/Application/ApplicationManagement.tsx
src/shared/Elements/ViewPDF.tsx

fix "view resume" button

---

package-lock.json
src/App.tsx
src/Dashboard/HackerDashboard.tsx
src/Dashboard/StaffDashboard.tsx
src/Dashboard/View.tsx
src/shared/Elements/Card.tsx
src/util/UserInfoHelperFunctions.ts

Incorporate `hidden` flag to allow cards to be hidden from view.
When `Application` card is not hidden:
When `Application` card is hidden:

Allow cards to be hidden

---

src/Dashboard/HackerDashboard.tsx
src/Dashboard/View.tsx
src/util/UserInfoHelperFunctions.ts

Adds subtitle to hacker dashboard page when applications are closed.

Add subtitle to applications being closed

---

src/Account/AccountManagement.tsx
src/Application/ApplicationManagement.tsx
src/shared/Elements/Button.tsx
src/shared/Form/SubmitBtn.tsx
src/shared/Form/index.ts

Add margin to bottom of submit btn, refactor code to HOC

---

src/shared/Elements/ViewPDF.tsx

Add 'resume not found' message

---

src/App.tsx

New routes should redirect to proper page after user has logged in.

Add redir after login state for multiple routes

---

src/ConfirmAttendance/ConfirmAttendance.tsx

changed to Friday, January 25 for final round of decisions
closes #350

update acceptance deadline

---

package-lock.json
package.json

- HCK-58
- Revert to old dependencies from like January bc the dashboard was not building right
- Bump critical fixes: `eslint-utils` and `handlebars`
- Will look into updating dependencies as we start working on this repo

Resolve breaking dependencies

---

.github/pull_request_template.md
README.md
docs/CONTRIBUTING.md

- HCK-56
- HCK-52
- Add contributing guide and link to it in README
- Add PR template (this one)
- Change repo name from `hackerapi-frontend` to `dashboard`
- Add folder structure to README
I don't know what else to add, maybe @erickzhao would you have a better idea on writing up a folder structure?

Add documentation

---

src/features/Account/ConfirmAccountContainer.tsx
src/features/ConfirmAttendance/ConfirmAttendance.tsx
src/features/Dashboard/DashboardText.tsx
src/features/Dashboard/HackerDashboard.tsx
src/features/Dashboard/SponsorDashboard.tsx
src/features/Dashboard/StaffDashboard.tsx

refactor Dashboard texts

---

src/shared/Form/RequiredInputLabel.tsx

HCK-168
Asterisks for required fields appear now
Removed duplicate display property
Fixes it

Asterisks appear now

---

docs/CHANGELOG.md

- HCK-179
- Update changelog with recent merge commits since last update

Update changelog with missing notes

---

docs/CHANGELOG.md
src/config/constants.ts
src/features/Application/ManageApplicationContainer.tsx
src/shared/Elements/Paragraph.tsx
src/shared/Form/Form.tsx
src/shared/Form/FormikElements/Checkbox.tsx
src/shared/Form/Label.tsx
src/shared/Form/StyledCreatableSelect.tsx
src/shared/Form/StyledSelect.tsx
src/shared/Styles/inputStyles.ts

- HCK-173
- Update application questions
- Fix form label to use Brown font

Update application questions

---

docs/CHANGELOG.md
src/features/Application/ManageApplicationContainer.tsx

HCK-181
Buttons are evenly spaced on all pages of application
Fixed the justify-content
It is THE way to fix it

Fixed spacing between buttons on application page

---

docs/CHANGELOG.md
docs/pull_request_template.md

- HCK-226
- Remove "Why are you choosing this approach?"
- Add screenshots and how to test sections

Update PR template

---

docs/CHANGELOG.md
src/features/Application/validationSchema.ts

- HCK-213
- Add integer validation for travel (prevents going to next page too)

Add integer validation for travel

---

docs/CHANGELOG.md
src/features/Application/ManageApplicationContainer.tsx

- HCK-227
- Proper error message displayed for privacy policy checkbox on application page
Error component associated with proper field now
N/A

Fixed checkmark validation

---

docs/CHANGELOG.md
src/features/Nav/Navbar.tsx

- HCK-204
- Fixed login button flashing when navigating to new tab
Render component once async method has finished
- Refresh page and see if button still flashes
Hard to get a screenshot/gif of it working properly:/

Fixed login button flashing

---

docs/CHANGELOG.md
src/App.tsx
src/features/Account/ConfirmAccountContainer.tsx
src/features/Nav/NavLink.tsx
src/features/Nav/Navbar.tsx
src/shared/HOC/withNavbar.tsx

- HCK-202
- Active page is highlighted in navbar
Updated the Navbar and withNavbar classes so that the active page is recorded and then highlighted.

Highlight link of active page on navbar

---

docs/CHANGELOG.md
src/features/Account/ConfirmAccountContainer.tsx
src/features/Dashboard/DashboardText.tsx

- HCK-210
- Change confirmed page text
- Add padding to confirmed account page layout

Update confirmed account page layout

---

docs/CHANGELOG.md
src/assets/images/telescope.svg
src/features/Account/ConfirmationEmailSentComponent.tsx
src/features/Status/StatusPage.tsx

- HCK-196
- Update confirm email page so that it matches figma style document

Restyle profile page

---

src/features/Status/StatusPage.tsx

fix where background image renders

---

docs/CHANGELOG.md
src/App.tsx
src/api/index.ts
src/api/travel.ts
src/assets/images/train.svg
src/config/APIRoute.ts
src/config/constants.ts
src/config/frontendRoutes.ts
src/config/index.ts
src/config/travel.ts
src/config/travelStatus.ts
src/features/Nav/Navbar.tsx
src/features/Status/StatusPage.tsx
src/features/Travel/Main.tsx
src/shared/Elements/H2.tsx
src/util/UserInfoHelperFunctions.tsx

- [HackerAPI Pull Request #39](https://github.com/hackmcgill/hackerAPI/pull/639)
- Added travel page that display's users status on travel and amount of money they are offered

Implement travel page

---

docs/CHANGELOG.md
src/features/Status/StatusPage.tsx

- Change api route used to confirm withdrawn status

Fix withdrawn button

---

docs/CHANGELOG.md
src/features/Travel/Main.tsx
src/shared/Styles/GlobalStyles.tsx

- HCK-
- Update global styles for `a` tag
- Update travel page text

Update travel page

---

docs/CHANGELOG.md
src/features/Travel/Main.tsx
src/util/UserInfoHelperFunctions.tsx

- HCK-
- Show travel link in navbar even if hacker didn't request any money (as bus details/whatever are on this page)
Change if statement

Show travel link even when requested money is 0

---

docs/CHANGELOG.md
src/config/constants.ts
src/features/Status/StatusPage.tsx

- Add RSVP close time
- Add close time to status page

Add RSVP close time

---

docs/CHANGELOG.md
src/features/Nav/LoginButton.tsx

- HCK-
- Remove scrollbar around login button

Remove scrollbar on login button

---

docs/CHANGELOG.md
src/features/Search/Search.tsx

- HCK-
- Changed the title of the sponsor search title

Small change to sponsor search helmet title

---

src/App.tsx
src/pages/Account/Confirm.tsx
src/pages/Account/Create.tsx
src/pages/Account/Edit.tsx
src/pages/Application/Confirm.tsx
src/pages/Application/Create.tsx
src/pages/Application/Edit.tsx
src/pages/Application/View/index.tsx
src/pages/Hacker/Checkin.tsx
src/pages/Hacker/Pass.tsx
src/pages/Login/index.tsx
src/pages/Password/Forgot.tsx
src/pages/Password/Reset.tsx
src/pages/Search/index.tsx
src/pages/Sponsor/Create.tsx
src/pages/Sponsor/Edit.tsx
src/pages/Team/index.tsx
src/pages/Travel/index.tsx
src/pages/index.tsx

closes # 833
-created copy of containers in the pages folder
-the new containers are the one being mapped to in App.tsx
-Don't know how to do the routing for '/admin/search' and '/sponsor/search' without having repeated code
-Not sure how '/application/view/:id' will capture the id
-Don't know which components should be refactored to a more general form

833 move components for nextjs routing

---

package-lock.json
src/features/Nav/Navbar.tsx

Change isOpen=true. Not sure what this boolean constant does, but it seems like when set to 'true', the burger nav is not present
fixes #845 
- Change `isOpen=true`
Run and load any webpage. The burger nav should no longer be open.
[![Image from Gyazo](https://i.gyazo.com/bdcf71170f66a6edeb1e94aa515d0f4b.gif)](https://gyazo.com/bdcf71170f66a6edeb1e94aa515d0f4b)

feat: set nav page to be closed by default for mobile

---

src/features/Account/ManageAccountForm.tsx
src/pages/Application/View/[id].tsx
src/shared/Elements/LinkDuo.tsx

- Saw several warnings in the chrome console. Fixed them in this CL.
- Confirm that every page that I changed still works. I checked on my end.

fix: minor formatting isssues, react-hook dependencies

---

src/api/settings.ts
src/config/constants.ts
src/features/Application/ManageApplicationContainer.tsx
src/features/Nav/Navbar.tsx
src/features/Status/StatusHeader.tsx
src/features/Status/StatusPage.tsx
src/shared/HOC/withHackerRedirect.tsx
src/util/UserInfoHelperFunctions.tsx
src/util/util.ts

fixes: #858 
- Add fetches to settings schema where necessary
- Use settings schema instead of APPLICATION_CLOSE_TIME and DECISION_CLOSE_TIME
- Remove APPLICATION_CLOSE_TIME and DECISION_CLOSE_TIME
- functionally nothing should've changed.
- Make sure the hackers in their proper states are seeing the right text

Wire in settings schema into places where we used APPLICATION_CLOSE_TIME and DECISION_CLOSE_TIME

---

src/shared/Elements/Button.tsx

- HCK- #878
- Adjust button styling make sure all permutations of disabled, outlined, loading, hover etc. interact properly
- Simplify code in Buttons.tsx
- Deprecate CallToAction & Tertiary Button variants, will display weirdly until all removed
Primary:
Primary outlined:
Secondary:
Secondary outlined:
All disabled:
All loading: (wheel is animated)
Hovers are handled appropriately too

feat: restyle buttons and simplify code

---

src/App.tsx
src/config/constants.ts
src/features/Team/JoinCreateTeam.tsx
src/features/Team/TeamDescription.tsx
src/features/Team/TeamView.tsx
src/pages/Team/index.tsx

- HCK- #896
- Fix teams page
- Change react helmet to avoid endless loop
- Still doing: investigating state update endless loops

fix: teams page on component mount

---

package-lock.json
src/features/Status/StatusCTA.tsx
src/features/Status/StatusCTAContainer.tsx

- HCK-#904
- Additional modal to confirm action if user is trying to withdraw
Not sure what the message should be, let me know if you want to change it!
[WITHDRAW]
[WITHDRAW - NO]
[WITHDRAW - YES]

feat: add modal if withdrawing

---

src/features/Nav/Links.tsx

- HCK- #901 
- Give navbar fixed position so it doesn't jump around (seemed to be some combination of flex display, sticky and fixed position going wonky in browser)

fix: navbar jumping sporadically

---

src/features/Account/ManageAccountForm.tsx

- HCK-#920 
- Login page should no longer redirect when creating an account with an already-existing email
- Added a couple of if-statements (not entirely sure why this works...doesn't seem to reach my if statement in `handleCreate()`
closes #920

fix: create page redirecting when email already exists

---

src/config/constants.ts
src/features/Application/ManageApplicationForm.tsx

- HCK- #913
- Add message to application review page asking hackers to mark themselves as going to our facebook event, should drive engagement

feat: implore hackers to mark themselves as going to our facebook event

---

src/index.tsx

- HCK- #820 
- Deregister service worker (https://create-react-app.dev/docs/making-a-progressive-web-app/#why-opt-in)

fix: deregister service worker

---

package-lock.json
src/features/Onboarding/GeneralOnboarding.tsx

- HCK-
Text, links, formatting etc. for sponsors dashboard

Sponsors dashboard update

---

src/features/Application/ManageApplicationForm.tsx

forgot to remove the attendance preference option for mchacks 9.

feat: remove attendance preference

---

src/features/Application/ManageApplicationForm.tsx

fix: remove unused type

---

package-lock.json
package.json
src/features/Application/ManageApplicationForm.tsx
src/features/Onboarding/DiscordOnboarding.tsx
src/features/Onboarding/GeneralOnboarding.tsx

chore: new release

---

src/config/constants.ts
src/features/Application/ManageApplicationForm.tsx

Remove Attendance Preference from Review Section

---

package-lock.json
package.json
src/App.tsx
src/api/account.ts
src/api/auth.ts
src/api/endpoint.ts
src/api/hacker.ts
src/api/search.ts
src/api/settings.ts
src/config/APIRoute.ts
src/config/settings.ts
src/config/userTypes.ts
src/features/Account/ManageAccountForm.tsx
src/features/Application/ManageApplicationForm.tsx
src/features/Dashboard/HackerDashboard.tsx
src/features/Invite/ExistingInvites.tsx
src/features/Nav/Navbar.tsx
src/features/Search/ResultsTable.tsx
src/features/Search/Search.tsx
src/features/Settings/SettingsForm.tsx
src/features/SingleHacker/SingleHackerModal.tsx
src/features/SingleHacker/SingleHackerView.tsx
src/features/Status/StatusCTA.tsx
src/features/Status/StatusCTAContainer.tsx
src/pages/Admin/Settings.tsx
src/util/UserInfoHelperFunctions.tsx
src/util/util.ts

- HCK-
- Fix account and settings update issues
- Fix hacker search functionality
- Update react-helmet to fix stack overflow bug

Fix account update, settings, and hacker search

---

src/App.tsx
src/config/constants.ts
src/pages/Travel/TravelStatusNone.tsx
src/pages/Travel/TravelStatusOffered.tsx
src/pages/Travel/index.tsx

feat: travel update (remove busses)

---

src/features/Onboarding/DiscordOnboarding.tsx
src/features/Onboarding/GeneralOnboarding.tsx
src/features/Onboarding/Onboarding.tsx

- HCK-
- Updates to the sponsor dashboard for the 10th edition. 

feat: updated sponsor dashboard

---

src/api/team.ts
src/config/APIRoute.ts
src/config/team.ts
src/features/Team/JoinCreateTeam.tsx
src/pages/Team/index.tsx

Brief changes to data types such as `teamId` to `team` and `id` to `identifier`. 
Part of `jacky/refactor` (typescript refactor)

fix: team dashboard fixes for joining, leaving and creating a team

---

src/App.tsx
src/config/constants.ts
src/config/userTypes.ts
src/features/Application/ManageApplicationForm.tsx
src/features/Application/validationSchema.ts
src/features/Nav/Navbar.tsx

- hackmcgill/hackerAPI#921
- Moved travel reimbursement to its own page and added disclaimer

Move travel reimbursement to its own page

---

src/api/api.ts
src/config/constants.ts

- Dashboard now uses development API when deployed in dev environment

Dashboard uses dev api when in dev environment

---

src/shared/Form/StyledCreatableSelect.tsx

- Changed cursor to text to make it more obvious that typing is permitted

Change cursor for CreatableSelect component

---

src/features/Application/validationSchema.ts

- Update min and max grad years
- Fix validation bugs for empty grad year and questions

Fix validation schema

---

src/config/constants.ts
src/config/degrees.ts
src/features/Application/ManageApplicationForm.tsx
src/shared/Form/FormikElements/Select.tsx
src/shared/Form/Label.tsx

chore: dev to v4

---

README.md
src/config/constants.ts
src/features/Account/ManageAccountForm.tsx
src/features/Application/ManageApplicationForm.tsx

- HCK-
- Removed facebook info
- Fixed typo
- Removed Netlify link on Readme
- Require phone number

Merge develop into main
