hackmcgill/dashboard

- src/components/applicationComponent.tsx
Fixes #238.
Prior to this, you would get an uncaught exception if you didn't type anything into the longform questions since their validation functions checked for `value.length`. I just added a guard to `value` to make sure it existed before proceeding to check its character length.
> Fix Yup Validation

- src/shared/Form/StyledSelect.tsx
Small fix. Realized that we forgot to copy a style over from one CSS component to another.
Before:
After:
> Remove left margin to align styled select with other inputs

- package-lock.json
- package.json
I ran `npm install` and `npm audit fix`.
Before:
```
audited 41823 packages in 11.269s
found 1 high severity vulnerability
run `npm audit fix` to fix them, or `npm audit` for details
```
After:
```
audited 41862 packages in 10.805s
found 0 vulnerabilities
```
> Update packages according to npm audit

- src/Search/Filters.tsx
- src/Search/Search.tsx
- src/config/searchParameter.ts
- src/util/util.ts
Add search query into url so that users can copy-paste queries to each other, and also other parts of the site can trigger queries. 
- Providing a search in the URL (such as http://localhost:1337/admin/search?q=[%7B%22param%22:%22accountId.gender%22,%22operation%22:%22in%22,%22value%22:[%22Male%22]%7D] ) triggers a search on load
- The filters are populated with the proper values that reflect the url
- When the filters change & submitted, the url is changed as well
> Feature/search: place search query in URL

- src/Team/Main.tsx
- src/api/team.ts
When we do not clear cache, the team page does not rerender to show the team information.
> Clear hacker cache when user joins team

- src/features/Account/ManageAccountContainer.tsx
- src/features/Application/ManageApplicationContainer.tsx
- src/features/Dashboard/HackerDashboard-old.tsx
- src/features/Dashboard/HackerDashboard.tsx
- src/features/Sidebar/Sidebar.tsx
- src/features/Sidebar/SidebarContainer.tsx
- src/features/Sidebar/SidebarItem.tsx
- src/features/Status/StatusPage.tsx
- src/features/Team/JoinCreateTeam.tsx
- src/features/Team/TeamDescription.tsx
- HCK-121
Implemented sidebar and revamped dashboard layout. It now just returns the status page initially and from there users can navigate to the desired tab using the sidebar.
Implementing the Sidebar element in the appropriate elements that require one (i.e. Application, Account, Home, Team containers). 
Was the quickest approach for immediate deployment.
I might have useless code commented out, heads up.
> Created sidebar that is always displayed on the side

- docs/CHANGELOG.md
- src/config/constants.ts
- src/config/degrees.ts
- src/config/gradYears.ts
- src/features/Application/ManageApplicationContainer.tsx
- src/features/Application/validationSchema.ts
- HCK-182
- HCK-180
- HCK-183
- Reorder degrees into chronological order
- Move travel label to `constants.ts`
- Remove `needsBus` from application (I don't think it'll break backend since the field isn't required but we need to remove it there anyways, see HCK-194)
- Add travel field validation
- Update graduation year validation to be **2019-2025**
- I removed `needsBus` bc it made `travel` a nested field that needed to be validated
- Update grad years b/c we aren't accepting non-students
How to test:
- Enter # in grad year field that's not 2020-2025 inclusive
- Enter # in travel field that's not 0-100 inclusive
> Update travel and grad year validation

- docs/CHANGELOG.md
- src/features/Application/ManageApplicationContainer.tsx
HCK-207
Changed `submit` to `update` based on whether hacker is creating or editing their application
Change the text to be displayed based on this.state.mode
It is THE way to fix it
> changed submit to update if hacker is editing their application

- docs/CHANGELOG.md
- src/shared/Form/FormikElements/Checkbox.tsx
- src/shared/Form/StyledCreatableSelect.tsx
- src/shared/Form/StyledSelect.tsx
- HCK-225
- Dropdown list should be above other elements now
Removed previous z-Index changes, and just changed the checkbox background to -1, as this was related to another ticket I fixed.
Doesn't cause issues with other elements
> dropdown list should be above all other elements now

- docs/CHANGELOG.md
- src/features/Application/validationSchema.ts
- HCK-230
- Github field allows any user name, not just starting with w's
Add the escape character
> Fixed URL validation for github

- docs/CHANGELOG.md
- src/config/constants.ts
- src/features/Status/StatusPage.tsx
- HCK-92
- Add string constants for each hacker status text
- Change text in `StatusPage.tsx` to use the new constants
- Change hacker status to `None` and `Applied` to see if the appropriate text shows up
- Other statuses haven't been updated for the status page yet (that'll be HCK-211)
- Read over text for spelling errors + that it's fine for UX
> Add status page text constants

- docs/CHANGELOG.md
- src/features/Dashboard/HackerDashboard.tsx
- src/features/Status/StatusPage.tsx
- HCK-200
- Confirm email component does not flash when navigating home now
- Make component render if async methods have finished.
- Refresh page and see if it flashes
Can't really make a gif/screenshot showing it working properly:/
> Fixed confirm email component flashing when navigating to homepage

- docs/CHANGELOG.md
- src/features/Account/ManageAccountContainer.tsx
- HCK-231
- Fix missing space in create/edit account site title
Go to `/account/edit` or `/account/create` and check site title has space
> Fix missing space in create/edit account site title

- src/App.tsx
- src/config/frontendRoutes.ts
fixes #652 
- HCK-
-added route from /.well-known/change-password to 'forgot password' page
-I think it only works on safari and not chrome because I can't change password from my chrome browser. Probably need to test using a mac and safari.
> added route for well known password change

- src/shared/Styles/GlobalStyles.tsx
- #825 
- added fallback font face in the global styles page
- googled the issue to find similar examples
> fix: add fallback font face during font render

- src/api/index.ts
- src/api/settings.ts
- src/config/APIRoute.ts
- src/config/index.ts
- src/config/settings.ts
fixes: #852
- create ISettings schema
- add API endpoint for schemas
Nothing uses this endpoint right now, so there is no way to test this atm.
no need.
> feat: Create client-side API endpoint for settings

- public/index.html
- src/App.tsx
- src/pages/Login/index.tsx
- src/shared/HOC/withBackground.tsx
- HCK- #876 
- Very slight (#fff to #f4f4f4) gradient background for pages, addable by wrapping a page in `withBackground()`
> feat: very slight gradient background via withBackground hoc

- package.json
- src/features/Application/ManageApplicationForm.tsx
- src/features/Application/ResumeComponent.tsx
- src/shared/Form/FileUpload.tsx
- HCK-#913
- Updated react-dropzone
- Fixed double picker problem
- Improve "View Resume" button visuals
- Maintain filename on resume component through page navigation
- Fixed resume set logic on page navigation
fixes #913
> Fix: 913 double resume picker

- src/App.tsx
- src/config/constants.ts
- src/features/Dashboard/View.tsx
- src/pages/Account/Confirm.tsx
- src/pages/_error.tsx
- HCK- #922 
- Use withBackground() for sponsor and staff dashboard pages, removing old background image so cards are clickable again
- Redo 404 page
- Update a couple buttons that were missed to use new style 
> feat: clean up staff/sponsor and 404 page

- src/features/Application/ManageApplicationForm.tsx
- HCK-#919 
- Back button should work again without breaking next page in `renderEducationFormik()`
- Added a placeholder reset button that is hidden through CSS
close #919
> fix: broken back button in renderPortfolioFormik

- src/config/frontendRoutes.ts
- src/features/Status/StatusCTA.tsx
- HCK-
- Remove left over button to access travel page. Commenting out everything travel related so doesn't happen again for the time being.
> fix: Removing button to access travel page

- package.json
- src/config/majors.ts
- src/features/Application/ManageApplicationForm.tsx
- Added "Other" option to Field of Study Select in Hacker Application and removed the ability to create an option. 
- Added Windows-specific commands to the package.json. Not sure if build works.
In majors.ts, added "Other" to the MajorsList.
In ManageApplicationForm.tsx, changed creatable={true} to creatable={false} for the Field of Study field.
In package.json, added Windows command "set" and && to "build" and "test". Not sure if build works.
> Replaced ability to "create" a major with "Other" option

- src/config/constants.ts
- src/features/Account/ManageAccountForm.tsx
- src/features/Application/ManageApplicationForm.tsx
- HCK-
- fixed review application typo 
- removed outdated facebook popup
- added phone number field on account creation
Changed some code
Check application review on dashboard. Check account creation field works and creates an account with a phone number Check if facebook popup appears/doesn't appear (shouldn't appear).
I only added the phone number element to the form because Tavi said there was a field for it in the db already. I'm assuming this is fine, please refer to the photo and check the change.
> Fix: Review application typo, outdated facebook popup, phone number field on account creation

- .yarnrc.yml
- src/features/Search/Search.tsx
https://github.com/hackmcgill/dashboard/issues/1021
- Removed Dribbble URL, Commented out Would you prefer to attend McHacks in person or virtually? and Travel
- Added (to staff only section)
- age
- dietary restrictions
- number of previous hackathons
- I authorize MLH to send me occasional emails about relevant events, career opportunities, and community announcements.
- [X ] New feature (non-breaking change which adds functionality)
> Improve hacker export feature
